FROM codercom/code-server:v2

RUN sudo apt-get update && sudo apt-get install -y curl apt-transport-https ca-certificates software-properties-common gnupg-agent vim zip jq iputils-ping \
      net-tools

# Install Kubectl
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list && \
    sudo apt-get update && \
    sudo apt-get install -y kubectl

# Install Helm
RUN curl -L https://git.io/get_helm.sh | bash

# Install Docker CLI
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" && \
    sudo apt-get update && \
    sudo apt-get install docker-ce-cli

# Install Consul CLI
RUN curl -sL https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_amd64.zip -o /tmp/consul.zip && \
    unzip /tmp/consul.zip && \
    sudo mv consul /usr/local/bin

# Install Go
RUN wget https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz -O /tmp/go1.13.tar.gz && \
    sudo tar -C /usr/local -xzf /tmp/go1.13.tar.gz && \
    rm /tmp/go1.13.tar.gz

ENV PATH="$PATH:/usr/local/go/bin"
ENV GOPATH="/home/coder/go"
ENV GO111MODULE="on"

# Install tools for VSCode
RUN go get github.com/mdempsky/gocode && \
    go get golang.org/x/tools/gopls && \
    go get github.com/uudashr/gopkgs/cmd/gopkgs && \
    go get github.com/ramya-rao-a/go-outline && \
    go get github.com/acroca/go-symbols && \
    go get golang.org/x/tools/cmd/guru && \
    go get golang.org/x/tools/cmd/gorename && \
    go get github.com/go-delve/delve/cmd/dlv && \
    go get github.com/stamblerre/gocode && \
    go get github.com/rogpeppe/godef && \
    go get github.com/sqs/goreturns && \
    go get golang.org/x/lint/golint && \
    go get github.com/uudashr/gopkgs/cmd/gopkgs && \
    go get github.com/stamblerre/gocode && \
    go build -i -o $GOPATH/bin/gocode-gomod github.com/stamblerre/gocode

# extensions to code-server
RUN code-server --install-extension ms-vscode.go
RUN code-server --install-extension redhat.vscode-yaml 
RUN code-server --install-extension wholroyd.hcl

# Symlink extensions for root user
RUN sudo mkdir -p /root/.local/share/code-server/extensions
RUN sudo ln -s /home/coder/.local/share/code-server/extensions/ms-vscode.go-0.11.4/ /root/.local/share/code-server/extensions
RUN sudo ln -s /home/coder/.local/share/code-server/extensions/redhat.vscode-yaml-0.5.3/ /root/.local/share/code-server/extensions
RUN sudo ln -s /home/coder/.local/share/code-server/extensions/wholroyd.hcl-0.0.4/ /root/.local/share/code-server/extensions

# Set the shell to bash
ENV SHELL=/bin/bash

# Make the default user admin
RUN sudo usermod -aG sudo coder

CMD ["code-server", "--allow-http", "--no-auth"]
