FROM ubuntu:latest

ENV TERM=xterm-256color

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
      curl \ 
      software-properties-common \
      zip \
      gnupg-agent && \
      apt-get clean && \
      apt-get autoremove --purge

# Install Kind
RUN curl -sLo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-$(uname)-amd64 && \
    chmod +x ./kind && \
    mv ./kind /usr/local/bin/kind

# Install k3d
RUN curl -s https://raw.githubusercontent.com/rancher/k3d/master/install.sh | bash

# Install Kubectl
RUN curl -sLO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin

# Install Helm
RUN curl -sL https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz -o ./helm.tar.gz && \
    tar -xzf ./helm.tar.gz && \
    mv ./linux-amd64/helm /usr/local/bin && \
    rm ./helm.tar.gz && \
    helm init -c

# Install Docker CLI
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" && \
    apt-get update && \
    apt-get install docker-ce-cli && \
    apt-get clean && \
    apt-get autoremove --purge

# Install Consul CLI
RUN curl -sL https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_amd64.zip -o consul.zip && \
    unzip consul.zip && \
    mv consul /usr/local/bin && \
    rm consul.zip
