FROM ubuntu:latest

ENV TERM=xterm-256color
ENV DOCKER_VERSION=18.03.1-ce
ENV KIND_VERSION=v0.5.1
ENV KUBECTL_VERSION=latest
ENV CONSUL_VERSION=1.6.1
ENV HELM_VERSION=v3.0.0-beta.4
ENV SQUASH_VERSION=v0.5.18
ENV LOOP_VERSION=v0.0.1
ENV GLOO_VERSION=v0.20.8

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
      curl \ 
      zip \
      vim \
      net-tools \
      dnsutils \
      ngrep \
      iputils-ping \
      gnupg-agent && \
      apt-get clean && \
      apt-get autoremove --purge

# Install Kind
RUN curl -sLo ./kind https://github.com/kubernetes-sigs/kind/releases/download/$KIND_VERSION/kind-$(uname)-amd64 && \
    chmod +x ./kind && \
    mv ./kind /usr/local/bin/kind

# Install K3d
RUN curl -s https://raw.githubusercontent.com/rancher/k3d/master/install.sh | bash

# Install Docker CLI
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz | \
tar zxvf - --strip 1 -C /usr/bin docker/docker

# Install Kubectl
RUN curl -sLO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin

# Install Helm
RUN curl -sL https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz -o ./helm.tar.gz && \
    tar -xzf ./helm.tar.gz && \
    mv ./linux-amd64/helm /usr/local/bin && \
    rm ./helm.tar.gz

# Install Consul CLI
RUN curl -sL https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip -o consul.zip && \
    unzip consul.zip && \
    mv consul /usr/local/bin && \
    rm consul.zip

# Install Squash
RUN curl -sL https://github.com/solo-io/squash/releases/download/$SQUASH_VERSION/squashctl-linux -o squashctl && \
    mv squashctl /usr/local/bin && \
    chmod +x /usr/local/bin/squashctl

# Install Gloo CLI
RUN curl -sL https://github.com/solo-io/gloo/releases/download/$GLOO_VERSION/glooctl-linux-amd64 -o glooctl && \
    mv glooctl /usr/local/bin && \
    chmod +x /usr/local/bin/glooctl

# Install preview of Loop CLI
RUN curl -sL https://github.com/solo-io/demos-gloo/releases/download/$LOOP_VERSION/loopctl-linux-amd64 -o  loopctl && \
    mv loopctl /usr/local/bin && \
    chmod +x /usr/local/bin/loopctl    
