#!/bin/bash -e

# Check that shipyard is installed if not install it
if ! [ -x "$(command -v yard)" ]; then
  VERSION=0.7.0

  echo "## Installing Shipyard Version: $VERSION" 
  echo ""

  echo "### Remove existing install"
  echo "#### You may be prompted for your password!###"
  sudo rm -f /usr/local/bin/yard
  sudo rm -rf $HOME/.shipyard
  echo ""

  echo "### Download application"
  wget https://github.com/nicholasjackson/shipyard/archive/v$VERSION.tar.gz -O /tmp/shipyard.tar.gz
  tar -zxf /tmp/shipyard.tar.gz -C /tmp/
  echo ""

  echo "### Install application config to $HOME/.shipyard"
  mv /tmp/shipyard-$VERSION/install $HOME/.shipyard
  echo ""

  echo "### Linking application to /usr/local/bin"
  echo "#### You may be prompted for your password!###"
  sudo ln -s $HOME/.shipyard/yard /usr/local/bin
  echo ""

  echo "## Instalation complete"
  echo "To create a local Kubernetes and Consul cluster run:"
  echo ""
  echo "yard up"
fi

/usr/local/bin/yard up --enable-consul false

echo "Shipyard running...."
echo ""

echo "Set the following environment variables to interact with Kubernetes and Vault"
echo ""

echo "export KUBECONFIG=\"\$HOME/.shipyard/yards/shipyard/kubeconfig.yml\""
echo "export VAULT_ADDR=\"http://localhost:8200\""
echo "export VAULT_TOKEN=\"root\""

echo ""
echo "You can also open the Vault UI in your browser"
echo "http://localhost:8200"