#!/bin/bash -e

# Check that shipyard is installed if not install it
if ! [ -x "$(command -v yard)" ]; then
  curl https://shipyard.demo.gs/install.sh | bash
fi

yard up --enable-consul false

echo "Shipyard running...."
echo "

echo "Set the following environment variables to interact with Kubernetes and Vault"
echo ""

echo "export KUBECONFIG=\"\$HOME/.shipyard/yards/shipyard/kubeconfig.yml\""
echo "export VAULT_ADDR=\"http://localhost:8200\""
echo "export VAULT_TOKEN=\"root\""

echo "You can also open the Vault UI in your browser"
echo "http://localhost:8200"